### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by danielrf121** [Bengejd/cordova-plugin-last-cam#1]
Good Morning,
I started a plugin test with an Ionic blank and am encountering this error: **ERROR Error: Uncaught (in promise): Class not found.**

<img width="689" alt="screen shot 2018-10-22 at 08 13 09" src="https://user-images.githubusercontent.com/15792968/47289975-a4881e80-d5d3-11e8-8fc0-827cdbdbc0e8.png">

This is the code on my screen:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { LastCam } from '@ionic-native/last-cam';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
  providers: [ LastCam ]
})
export class HomePage {

  cameraOpts: any = {
    x: 0,
    y: 0,
    width: window.screen.width,
    height: window.screen.height,
    camera: 'rear'
  };

  constructor(
    public navCtrl: NavController,
    private lastCam: LastCam
  ) {
  }

  ionViewDidEnter() {
    // start camera
    this.lastCam.startCamera(this.cameraOpts);
  }

  teste() {
    this.lastCam.startVideoCapture().then((fileUri: any) => {
      console.log('Video Capture started', fileUri);
    })
    .catch(err => { 
      console.log(err);
    });
  }
}
```

My project environment:
ionic: 3.19.0
ionic-angular: 3.9.2
cordova 6.5.0
node 8.12.0

Device: Samsung galaxy s9+

Anyway, good initiative, since we have many problems with media-capture and we do not have many options of plugins to use.

**Comment by Bengejd** [comment]
Unfortunately, right now LastCam is IOS only, but PR's are welcome.
