### ISSUE TITLE
Analysing frames of preview

### ISSUE THREAD

**Issue by 3kumar** [Bengejd/cordova-plugin-last-cam#3]
How can we process the frames of the preview using this plugin? Is the most desired functionality. Could somebody please add this functionality?

**Comment by Bengejd** [comment]
Not sure I understand what you're trying to accomplish since you didn't go into specifics about your issue...

**Comment by 3kumar** [comment]
> Not sure I understand what you're trying to accomplish since you didn't go into specifics about your issue...

I want to perform snapchat like Augmented Reality on faces.For that I need to process each frame shown in Preview. As, I dont want to store the preview as video and perform the analysis later. I am expecting something which provides you the frames of cameraview on camerastart callback.

I hope, this made the issue clear.

**Comment by Bengejd** [comment]
That is way out of scope for this plugin, and not something that I will be focusing on, personally. Feel free to create a pull request if you figure it out though!
